name: scalastyle-validate
description: 'Validates Scala Code'

inputs:
  scala-code-directory:
    description: 'Path to the Scala code'
    required: true
  scalastye-config-directory:
    description: 'Path to the Scalastyle configuration file'
    required: true
  scalastyle-directory:
    description: 'Path where the Scalastyle jar is downloaded. Default value assumes is in the same working directory'
    required: false
    default: 'scalastyle.jar'

runs:
  using: "composite"
  steps:
    - run: | 
        scala_output=$(java -jar ${{ inputs.scalastyle-directory }} --config ${{ inputs.scalastye-config-directory }} ${{ inputs.cala-code-directory }})
        echo $scala_output
        if [[ $scala_output != *"0 warning"* ]]; then
          echo "Error!" > "Check scala style"
          exit 64
        else
          echo "No scala styling errors or warnings found" 
        fi
      shell: bash
